// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/file_storage.proto

package filestorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Типы файлов
type FileType int32

const (
	FileType_FILE_TYPE_UNSPECIFIED FileType = 0
	FileType_FILE_TYPE_AVATAR      FileType = 1
	FileType_FILE_TYPE_CARD_IMAGE  FileType = 2
	FileType_FILE_TYPE_DOCUMENT    FileType = 3
	FileType_FILE_TYPE_OTHER       FileType = 4
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_UNSPECIFIED",
		1: "FILE_TYPE_AVATAR",
		2: "FILE_TYPE_CARD_IMAGE",
		3: "FILE_TYPE_DOCUMENT",
		4: "FILE_TYPE_OTHER",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_UNSPECIFIED": 0,
		"FILE_TYPE_AVATAR":      1,
		"FILE_TYPE_CARD_IMAGE":  2,
		"FILE_TYPE_DOCUMENT":    3,
		"FILE_TYPE_OTHER":       4,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_file_storage_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_proto_file_storage_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{0}
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileType      FileType               `protobuf:"varint,4,opt,name=file_type,json=fileType,proto3,enum=filestorage.FileType" json:"file_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadFileRequest) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *UploadFileRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileType      FileType               `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=filestorage.FileType" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadFileResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadFileResponse) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *UploadFileResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadFileResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadFileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UploadInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileType      FileType               `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=filestorage.FileType" json:"file_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadInitRequest) Reset() {
	*x = UploadInitRequest{}
	mi := &file_proto_file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInitRequest) ProtoMessage() {}

func (x *UploadInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInitRequest.ProtoReflect.Descriptor instead.
func (*UploadInitRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadInitRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadInitRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadInitRequest) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *UploadInitRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UploadInitRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type UploadInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadInitResponse) Reset() {
	*x = UploadInitResponse{}
	mi := &file_proto_file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInitResponse) ProtoMessage() {}

func (x *UploadInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInitResponse.ProtoReflect.Descriptor instead.
func (*UploadInitResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *UploadInitResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadInitResponse) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *UploadInitResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type UploadPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PartNumber    int32                  `protobuf:"varint,2,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartRequest) Reset() {
	*x = UploadPartRequest{}
	mi := &file_proto_file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartRequest) ProtoMessage() {}

func (x *UploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartRequest.ProtoReflect.Descriptor instead.
func (*UploadPartRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadPartRequest) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadPartRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ETag          string                 `protobuf:"bytes,1,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartResponse) Reset() {
	*x = UploadPartResponse{}
	mi := &file_proto_file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartResponse) ProtoMessage() {}

func (x *UploadPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartResponse.ProtoReflect.Descriptor instead.
func (*UploadPartResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *UploadPartResponse) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

type UploadPartInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	ETag          string                 `protobuf:"bytes,2,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartInfo) Reset() {
	*x = UploadPartInfo{}
	mi := &file_proto_file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartInfo) ProtoMessage() {}

func (x *UploadPartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartInfo.ProtoReflect.Descriptor instead.
func (*UploadPartInfo) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *UploadPartInfo) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadPartInfo) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

type UploadCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Parts         []*UploadPartInfo      `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCompleteRequest) Reset() {
	*x = UploadCompleteRequest{}
	mi := &file_proto_file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCompleteRequest) ProtoMessage() {}

func (x *UploadCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCompleteRequest.ProtoReflect.Descriptor instead.
func (*UploadCompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *UploadCompleteRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadCompleteRequest) GetParts() []*UploadPartInfo {
	if x != nil {
		return x.Parts
	}
	return nil
}

type UploadCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileType      FileType               `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=filestorage.FileType" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCompleteResponse) Reset() {
	*x = UploadCompleteResponse{}
	mi := &file_proto_file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCompleteResponse) ProtoMessage() {}

func (x *UploadCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCompleteResponse.ProtoReflect.Descriptor instead.
func (*UploadCompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *UploadCompleteResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadCompleteResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadCompleteResponse) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *UploadCompleteResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadCompleteResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadCompleteResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UploadAbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAbortRequest) Reset() {
	*x = UploadAbortRequest{}
	mi := &file_proto_file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAbortRequest) ProtoMessage() {}

func (x *UploadAbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAbortRequest.ProtoReflect.Descriptor instead.
func (*UploadAbortRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *UploadAbortRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type UploadAbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAbortResponse) Reset() {
	*x = UploadAbortResponse{}
	mi := &file_proto_file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAbortResponse) ProtoMessage() {}

func (x *UploadAbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAbortResponse.ProtoReflect.Descriptor instead.
func (*UploadAbortResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{10}
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FileType      FileType               `protobuf:"varint,4,opt,name=file_type,json=fileType,proto3,enum=filestorage.FileType" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetFileResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *GetFileResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetFileResponse) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *GetFileResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GetFileResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetFileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_storage_proto_rawDescGZIP(), []int{14}
}

var File_proto_file_storage_proto protoreflect.FileDescriptor

const file_proto_file_storage_proto_rawDesc = "" +
	"\n" +
	"\x18proto/file_storage.proto\x12\vfilestorage\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x122\n" +
	"\tfile_type\x18\x04 \x01(\x0e2\x15.filestorage.FileTypeR\bfileType\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\"\xf1\x01\n" +
	"\x12UploadFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x122\n" +
	"\tfile_type\x18\x03 \x01(\x0e2\x15.filestorage.FileTypeR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbb\x01\n" +
	"\x11UploadInitRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x122\n" +
	"\tfile_type\x18\x03 \x01(\x0e2\x15.filestorage.FileTypeR\bfileType\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\"s\n" +
	"\x12UploadInitResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x03R\tchunkSize\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\"e\n" +
	"\x11UploadPartRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1f\n" +
	"\vpart_number\x18\x02 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\")\n" +
	"\x12UploadPartResponse\x12\x13\n" +
	"\x05e_tag\x18\x01 \x01(\tR\x04eTag\"F\n" +
	"\x0eUploadPartInfo\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x13\n" +
	"\x05e_tag\x18\x02 \x01(\tR\x04eTag\"g\n" +
	"\x15UploadCompleteRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x121\n" +
	"\x05parts\x18\x02 \x03(\v2\x1b.filestorage.UploadPartInfoR\x05parts\"\xf5\x01\n" +
	"\x16UploadCompleteResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x122\n" +
	"\tfile_type\x18\x03 \x01(\x0e2\x15.filestorage.FileTypeR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"1\n" +
	"\x12UploadAbortRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"\x15\n" +
	"\x13UploadAbortResponse\")\n" +
	"\x0eGetFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x89\x02\n" +
	"\x0fGetFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x122\n" +
	"\tfile_type\x18\x04 \x01(\x0e2\x15.filestorage.FileTypeR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\",\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x14\n" +
	"\x12DeleteFileResponse*\x82\x01\n" +
	"\bFileType\x12\x19\n" +
	"\x15FILE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FILE_TYPE_AVATAR\x10\x01\x12\x18\n" +
	"\x14FILE_TYPE_CARD_IMAGE\x10\x02\x12\x16\n" +
	"\x12FILE_TYPE_DOCUMENT\x10\x03\x12\x13\n" +
	"\x0fFILE_TYPE_OTHER\x10\x042\xc3\x04\n" +
	"\x12FileStorageService\x12M\n" +
	"\n" +
	"UploadFile\x12\x1e.filestorage.UploadFileRequest\x1a\x1f.filestorage.UploadFileResponse\x12M\n" +
	"\n" +
	"UploadInit\x12\x1e.filestorage.UploadInitRequest\x1a\x1f.filestorage.UploadInitResponse\x12M\n" +
	"\n" +
	"UploadPart\x12\x1e.filestorage.UploadPartRequest\x1a\x1f.filestorage.UploadPartResponse\x12Y\n" +
	"\x0eUploadComplete\x12\".filestorage.UploadCompleteRequest\x1a#.filestorage.UploadCompleteResponse\x12P\n" +
	"\vUploadAbort\x12\x1f.filestorage.UploadAbortRequest\x1a .filestorage.UploadAbortResponse\x12D\n" +
	"\aGetFile\x12\x1b.filestorage.GetFileRequest\x1a\x1c.filestorage.GetFileResponse\x12M\n" +
	"\n" +
	"DeleteFile\x12\x1e.filestorage.DeleteFileRequest\x1a\x1f.filestorage.DeleteFileResponseB?Z=github.com/karto4ki/karto4ki-backend/shared/proto;filestorageb\x06proto3"

var (
	file_proto_file_storage_proto_rawDescOnce sync.Once
	file_proto_file_storage_proto_rawDescData []byte
)

func file_proto_file_storage_proto_rawDescGZIP() []byte {
	file_proto_file_storage_proto_rawDescOnce.Do(func() {
		file_proto_file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_storage_proto_rawDesc), len(file_proto_file_storage_proto_rawDesc)))
	})
	return file_proto_file_storage_proto_rawDescData
}

var file_proto_file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_file_storage_proto_goTypes = []any{
	(FileType)(0),                  // 0: filestorage.FileType
	(*UploadFileRequest)(nil),      // 1: filestorage.UploadFileRequest
	(*UploadFileResponse)(nil),     // 2: filestorage.UploadFileResponse
	(*UploadInitRequest)(nil),      // 3: filestorage.UploadInitRequest
	(*UploadInitResponse)(nil),     // 4: filestorage.UploadInitResponse
	(*UploadPartRequest)(nil),      // 5: filestorage.UploadPartRequest
	(*UploadPartResponse)(nil),     // 6: filestorage.UploadPartResponse
	(*UploadPartInfo)(nil),         // 7: filestorage.UploadPartInfo
	(*UploadCompleteRequest)(nil),  // 8: filestorage.UploadCompleteRequest
	(*UploadCompleteResponse)(nil), // 9: filestorage.UploadCompleteResponse
	(*UploadAbortRequest)(nil),     // 10: filestorage.UploadAbortRequest
	(*UploadAbortResponse)(nil),    // 11: filestorage.UploadAbortResponse
	(*GetFileRequest)(nil),         // 12: filestorage.GetFileRequest
	(*GetFileResponse)(nil),        // 13: filestorage.GetFileResponse
	(*DeleteFileRequest)(nil),      // 14: filestorage.DeleteFileRequest
	(*DeleteFileResponse)(nil),     // 15: filestorage.DeleteFileResponse
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_proto_file_storage_proto_depIdxs = []int32{
	0,  // 0: filestorage.UploadFileRequest.file_type:type_name -> filestorage.FileType
	0,  // 1: filestorage.UploadFileResponse.file_type:type_name -> filestorage.FileType
	16, // 2: filestorage.UploadFileResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: filestorage.UploadInitRequest.file_type:type_name -> filestorage.FileType
	7,  // 4: filestorage.UploadCompleteRequest.parts:type_name -> filestorage.UploadPartInfo
	0,  // 5: filestorage.UploadCompleteResponse.file_type:type_name -> filestorage.FileType
	16, // 6: filestorage.UploadCompleteResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: filestorage.GetFileResponse.file_type:type_name -> filestorage.FileType
	16, // 8: filestorage.GetFileResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 9: filestorage.FileStorageService.UploadFile:input_type -> filestorage.UploadFileRequest
	3,  // 10: filestorage.FileStorageService.UploadInit:input_type -> filestorage.UploadInitRequest
	5,  // 11: filestorage.FileStorageService.UploadPart:input_type -> filestorage.UploadPartRequest
	8,  // 12: filestorage.FileStorageService.UploadComplete:input_type -> filestorage.UploadCompleteRequest
	10, // 13: filestorage.FileStorageService.UploadAbort:input_type -> filestorage.UploadAbortRequest
	12, // 14: filestorage.FileStorageService.GetFile:input_type -> filestorage.GetFileRequest
	14, // 15: filestorage.FileStorageService.DeleteFile:input_type -> filestorage.DeleteFileRequest
	2,  // 16: filestorage.FileStorageService.UploadFile:output_type -> filestorage.UploadFileResponse
	4,  // 17: filestorage.FileStorageService.UploadInit:output_type -> filestorage.UploadInitResponse
	6,  // 18: filestorage.FileStorageService.UploadPart:output_type -> filestorage.UploadPartResponse
	9,  // 19: filestorage.FileStorageService.UploadComplete:output_type -> filestorage.UploadCompleteResponse
	11, // 20: filestorage.FileStorageService.UploadAbort:output_type -> filestorage.UploadAbortResponse
	13, // 21: filestorage.FileStorageService.GetFile:output_type -> filestorage.GetFileResponse
	15, // 22: filestorage.FileStorageService.DeleteFile:output_type -> filestorage.DeleteFileResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_file_storage_proto_init() }
func file_proto_file_storage_proto_init() {
	if File_proto_file_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_storage_proto_rawDesc), len(file_proto_file_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_storage_proto_goTypes,
		DependencyIndexes: file_proto_file_storage_proto_depIdxs,
		EnumInfos:         file_proto_file_storage_proto_enumTypes,
		MessageInfos:      file_proto_file_storage_proto_msgTypes,
	}.Build()
	File_proto_file_storage_proto = out.File
	file_proto_file_storage_proto_goTypes = nil
	file_proto_file_storage_proto_depIdxs = nil
}
