services:
  identity-service:
    build: ./identity-service
    container_name: identity-service
    volumes:
      - ./identity-service/config.yml:/app/config.yml:ro
      - ./keys:/app/keys:ro
    environment:
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - USER_SERVICE_ADDR=user-service-mock:50051
    depends_on:
      - identity-redis
      - mock-userservice
  identity-redis:
    image: redis:latest
    volumes:
      - identity_redis_data:/data
    restart: on-failure
  
  mock-userservice:
    build:
      context: ./mock-userservice
      dockerfile: Dockerfile.mock
    container_name: mock-userservice
    ports:
      - "50051:50051"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - identity-service

volumes:
  identity_redis_data: