// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/card/card.proto

package card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CardCount     int32                  `protobuf:"varint,6,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardSet) Reset() {
	*x = CardSet{}
	mi := &file_proto_card_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardSet) ProtoMessage() {}

func (x *CardSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardSet.ProtoReflect.Descriptor instead.
func (*CardSet) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *CardSet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardSet) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CardSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardSet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CardSet) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CardSet) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

func (x *CardSet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CardSet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCardSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardSetRequest) Reset() {
	*x = CreateCardSetRequest{}
	mi := &file_proto_card_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardSetRequest) ProtoMessage() {}

func (x *CreateCardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardSetRequest.ProtoReflect.Descriptor instead.
func (*CreateCardSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardSetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateCardSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCardSetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCardSetRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CreateCardSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           *CardSet               `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardSetResponse) Reset() {
	*x = CreateCardSetResponse{}
	mi := &file_proto_card_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardSetResponse) ProtoMessage() {}

func (x *CreateCardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardSetResponse.ProtoReflect.Descriptor instead.
func (*CreateCardSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCardSetResponse) GetSet() *CardSet {
	if x != nil {
		return x.Set
	}
	return nil
}

type GetCardSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetId         string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardSetRequest) Reset() {
	*x = GetCardSetRequest{}
	mi := &file_proto_card_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardSetRequest) ProtoMessage() {}

func (x *GetCardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardSetRequest.ProtoReflect.Descriptor instead.
func (*GetCardSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardSetRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *GetCardSetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetCardSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           *CardSet               `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardSetResponse) Reset() {
	*x = GetCardSetResponse{}
	mi := &file_proto_card_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardSetResponse) ProtoMessage() {}

func (x *GetCardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardSetResponse.ProtoReflect.Descriptor instead.
func (*GetCardSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardSetResponse) GetSet() *CardSet {
	if x != nil {
		return x.Set
	}
	return nil
}

type UpdateCardSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetId         string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardSetRequest) Reset() {
	*x = UpdateCardSetRequest{}
	mi := &file_proto_card_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardSetRequest) ProtoMessage() {}

func (x *UpdateCardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCardSetRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *UpdateCardSetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UpdateCardSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCardSetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCardSetRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type UpdateCardSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           *CardSet               `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardSetResponse) Reset() {
	*x = UpdateCardSetResponse{}
	mi := &file_proto_card_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardSetResponse) ProtoMessage() {}

func (x *UpdateCardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardSetResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCardSetResponse) GetSet() *CardSet {
	if x != nil {
		return x.Set
	}
	return nil
}

type DeleteCardSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetId         string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardSetRequest) Reset() {
	*x = DeleteCardSetRequest{}
	mi := &file_proto_card_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardSetRequest) ProtoMessage() {}

func (x *DeleteCardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCardSetRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *DeleteCardSetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type DeleteCardSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardSetResponse) Reset() {
	*x = DeleteCardSetResponse{}
	mi := &file_proto_card_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardSetResponse) ProtoMessage() {}

func (x *DeleteCardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{8}
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SetId         string                 `protobuf:"bytes,2,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	Front         string                 `protobuf:"bytes,3,opt,name=front,proto3" json:"front,omitempty"`
	Back          string                 `protobuf:"bytes,4,opt,name=back,proto3" json:"back,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,6,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_card_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{9}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *Card) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *Card) GetBack() string {
	if x != nil {
		return x.Back
	}
	return ""
}

func (x *Card) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Card) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Card) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetId         string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	Front         string                 `protobuf:"bytes,2,opt,name=front,proto3" json:"front,omitempty"`
	Back          string                 `protobuf:"bytes,3,opt,name=back,proto3" json:"back,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,5,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_proto_card_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCardRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *CreateCardRequest) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *CreateCardRequest) GetBack() string {
	if x != nil {
		return x.Back
	}
	return ""
}

func (x *CreateCardRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateCardRequest) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_proto_card_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_proto_card_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{12}
}

func (x *GetCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_proto_card_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{13}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Front         string                 `protobuf:"bytes,2,opt,name=front,proto3" json:"front,omitempty"`
	Back          string                 `protobuf:"bytes,3,opt,name=back,proto3" json:"back,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,5,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_proto_card_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateCardRequest) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *UpdateCardRequest) GetBack() string {
	if x != nil {
		return x.Back
	}
	return ""
}

func (x *UpdateCardRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateCardRequest) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

type UpdateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_proto_card_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_proto_card_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_proto_card_card_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_card_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_card_proto_rawDescGZIP(), []int{17}
}

var File_proto_card_card_proto protoreflect.FileDescriptor

const file_proto_card_card_proto_rawDesc = "" +
	"\n" +
	"\x15proto/card/card.proto\x12\x04card\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n" +
	"\aCardSet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"card_count\x18\x06 \x01(\x05R\tcardCount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x84\x01\n" +
	"\x14CreateCardSetRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\"8\n" +
	"\x15CreateCardSetResponse\x12\x1f\n" +
	"\x03set\x18\x01 \x01(\v2\r.card.CardSetR\x03set\"E\n" +
	"\x11GetCardSetRequest\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"5\n" +
	"\x12GetCardSetResponse\x12\x1f\n" +
	"\x03set\x18\x01 \x01(\v2\r.card.CardSetR\x03set\"\x9b\x01\n" +
	"\x14UpdateCardSetRequest\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\"8\n" +
	"\x15UpdateCardSetResponse\x12\x1f\n" +
	"\x03set\x18\x01 \x01(\v2\r.card.CardSetR\x03set\"H\n" +
	"\x14DeleteCardSetRequest\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"\x17\n" +
	"\x15DeleteCardSetResponse\"\x87\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06set_id\x18\x02 \x01(\tR\x05setId\x12\x14\n" +
	"\x05front\x18\x03 \x01(\tR\x05front\x12\x12\n" +
	"\x04back\x18\x04 \x01(\tR\x04back\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\taudio_url\x18\x06 \x01(\tR\baudioUrl\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8e\x01\n" +
	"\x11CreateCardRequest\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12\x14\n" +
	"\x05front\x18\x02 \x01(\tR\x05front\x12\x12\n" +
	"\x04back\x18\x03 \x01(\tR\x04back\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\taudio_url\x18\x05 \x01(\tR\baudioUrl\"4\n" +
	"\x12CreateCardResponse\x12\x1e\n" +
	"\x04card\x18\x01 \x01(\v2\n" +
	".card.CardR\x04card\")\n" +
	"\x0eGetCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"1\n" +
	"\x0fGetCardResponse\x12\x1e\n" +
	"\x04card\x18\x01 \x01(\v2\n" +
	".card.CardR\x04card\"\x90\x01\n" +
	"\x11UpdateCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05front\x18\x02 \x01(\tR\x05front\x12\x12\n" +
	"\x04back\x18\x03 \x01(\tR\x04back\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\taudio_url\x18\x05 \x01(\tR\baudioUrl\"4\n" +
	"\x12UpdateCardResponse\x12\x1e\n" +
	"\x04card\x18\x01 \x01(\v2\n" +
	".card.CardR\x04card\",\n" +
	"\x11DeleteCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\x14\n" +
	"\x12DeleteCardResponse2\xa7\x04\n" +
	"\vCardService\x12H\n" +
	"\rCreateCardSet\x12\x1a.card.CreateCardSetRequest\x1a\x1b.card.CreateCardSetResponse\x12?\n" +
	"\n" +
	"GetCardSet\x12\x17.card.GetCardSetRequest\x1a\x18.card.GetCardSetResponse\x12H\n" +
	"\rUpdateCardSet\x12\x1a.card.UpdateCardSetRequest\x1a\x1b.card.UpdateCardSetResponse\x12H\n" +
	"\rDeleteCardSet\x12\x1a.card.DeleteCardSetRequest\x1a\x1b.card.DeleteCardSetResponse\x12?\n" +
	"\n" +
	"CreateCard\x12\x17.card.CreateCardRequest\x1a\x18.card.CreateCardResponse\x126\n" +
	"\aGetCard\x12\x14.card.GetCardRequest\x1a\x15.card.GetCardResponse\x12?\n" +
	"\n" +
	"UpdateCard\x12\x17.card.UpdateCardRequest\x1a\x18.card.UpdateCardResponse\x12?\n" +
	"\n" +
	"DeleteCard\x12\x17.card.DeleteCardRequest\x1a\x18.card.DeleteCardResponseB=Z;github.com/karto4ki/karto4ki-backend/shared/proto/card;cardb\x06proto3"

var (
	file_proto_card_card_proto_rawDescOnce sync.Once
	file_proto_card_card_proto_rawDescData []byte
)

func file_proto_card_card_proto_rawDescGZIP() []byte {
	file_proto_card_card_proto_rawDescOnce.Do(func() {
		file_proto_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_card_card_proto_rawDesc), len(file_proto_card_card_proto_rawDesc)))
	})
	return file_proto_card_card_proto_rawDescData
}

var file_proto_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_card_card_proto_goTypes = []any{
	(*CardSet)(nil),               // 0: card.CardSet
	(*CreateCardSetRequest)(nil),  // 1: card.CreateCardSetRequest
	(*CreateCardSetResponse)(nil), // 2: card.CreateCardSetResponse
	(*GetCardSetRequest)(nil),     // 3: card.GetCardSetRequest
	(*GetCardSetResponse)(nil),    // 4: card.GetCardSetResponse
	(*UpdateCardSetRequest)(nil),  // 5: card.UpdateCardSetRequest
	(*UpdateCardSetResponse)(nil), // 6: card.UpdateCardSetResponse
	(*DeleteCardSetRequest)(nil),  // 7: card.DeleteCardSetRequest
	(*DeleteCardSetResponse)(nil), // 8: card.DeleteCardSetResponse
	(*Card)(nil),                  // 9: card.Card
	(*CreateCardRequest)(nil),     // 10: card.CreateCardRequest
	(*CreateCardResponse)(nil),    // 11: card.CreateCardResponse
	(*GetCardRequest)(nil),        // 12: card.GetCardRequest
	(*GetCardResponse)(nil),       // 13: card.GetCardResponse
	(*UpdateCardRequest)(nil),     // 14: card.UpdateCardRequest
	(*UpdateCardResponse)(nil),    // 15: card.UpdateCardResponse
	(*DeleteCardRequest)(nil),     // 16: card.DeleteCardRequest
	(*DeleteCardResponse)(nil),    // 17: card.DeleteCardResponse
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_proto_card_card_proto_depIdxs = []int32{
	18, // 0: card.CardSet.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: card.CardSet.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: card.CreateCardSetResponse.set:type_name -> card.CardSet
	0,  // 3: card.GetCardSetResponse.set:type_name -> card.CardSet
	0,  // 4: card.UpdateCardSetResponse.set:type_name -> card.CardSet
	18, // 5: card.Card.created_at:type_name -> google.protobuf.Timestamp
	18, // 6: card.Card.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 7: card.CreateCardResponse.card:type_name -> card.Card
	9,  // 8: card.GetCardResponse.card:type_name -> card.Card
	9,  // 9: card.UpdateCardResponse.card:type_name -> card.Card
	1,  // 10: card.CardService.CreateCardSet:input_type -> card.CreateCardSetRequest
	3,  // 11: card.CardService.GetCardSet:input_type -> card.GetCardSetRequest
	5,  // 12: card.CardService.UpdateCardSet:input_type -> card.UpdateCardSetRequest
	7,  // 13: card.CardService.DeleteCardSet:input_type -> card.DeleteCardSetRequest
	10, // 14: card.CardService.CreateCard:input_type -> card.CreateCardRequest
	12, // 15: card.CardService.GetCard:input_type -> card.GetCardRequest
	14, // 16: card.CardService.UpdateCard:input_type -> card.UpdateCardRequest
	16, // 17: card.CardService.DeleteCard:input_type -> card.DeleteCardRequest
	2,  // 18: card.CardService.CreateCardSet:output_type -> card.CreateCardSetResponse
	4,  // 19: card.CardService.GetCardSet:output_type -> card.GetCardSetResponse
	6,  // 20: card.CardService.UpdateCardSet:output_type -> card.UpdateCardSetResponse
	8,  // 21: card.CardService.DeleteCardSet:output_type -> card.DeleteCardSetResponse
	11, // 22: card.CardService.CreateCard:output_type -> card.CreateCardResponse
	13, // 23: card.CardService.GetCard:output_type -> card.GetCardResponse
	15, // 24: card.CardService.UpdateCard:output_type -> card.UpdateCardResponse
	17, // 25: card.CardService.DeleteCard:output_type -> card.DeleteCardResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_card_card_proto_init() }
func file_proto_card_card_proto_init() {
	if File_proto_card_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_card_card_proto_rawDesc), len(file_proto_card_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_card_proto_goTypes,
		DependencyIndexes: file_proto_card_card_proto_depIdxs,
		MessageInfos:      file_proto_card_card_proto_msgTypes,
	}.Build()
	File_proto_card_card_proto = out.File
	file_proto_card_card_proto_goTypes = nil
	file_proto_card_card_proto_depIdxs = nil
}
