jwt:
  signing_method: RS256
  lifetime: 3m
  issuer: identity_service
  audience:
    - filestorage_service
  key_file_path: /app/keys/rsa.pub
http_port: 8081
redis:
  addr: redis:6379
  password: ""
  db: 0
idempotency:
  data_exp: 10m
upload:
  file_size_limit: 10485760 # 10MB для простой загрузки
multipart_upload:
  min_file_size: 10485760 # 10MB - минимальный размер для multipart
  max_part_size: 104857600 # 100MB - максимальный размер части
  max_file_size: 10485760 # 10MB - максимальный размер для простой загрузки
s3:
  bucket: karto4ki-files
  url_prefix: http://minio:9000/karto4ki-files/
  endpoint: minio:9000
  region: us-east-1
aws:
  access_key_id: minioadmin
  secret_access_key: minioadmin
grpc_service:
  port: 9090
