access_token:
  signing_method: HS512
  lifetime: 5m
  issuer: identity_service
  audience: 
    - client
  key_file_path: /app/keys/sym
refresh_token:
  signing_method: HS512
  lifetime: 720h 
  issuer: identity_service
  audience: 
    - client
  key_file_path: /app/keys/sym
internal_token:
  signing_method: RS256
  lifetime: 1m
  issuer: identity_service
  audience: 
    - identity_service
  key_file_path: /app/keys/rsa
invalidated_token_storage:
  exp: 720h 
userservice:
  grpc_addr: userservice:50051
redis:
  addr: identity-redis:6379
  password: ""
  db: 0
signin_meta:
  lifetime: 2m
signup:
  code_ttl: 5m
oauth:
  google_client_id: "141687630390-bgi0d3tqstk7rls6umcdludg14einjel.apps.googleusercontent.com"
  apple_client_id: "com.lzkgmr.karto4ki"
idempotency:
  data_exp: 10m
  lock_ttl: 30s
email_code:
  send_frequency: 1m
grpc_service:
  port: 50051