// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user.proto

package userservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveProviderFromUserStatus int32

const (
	RemoveProviderFromUserStatus_REMOVE_PROVIDER_SUCCESS           RemoveProviderFromUserStatus = 0
	RemoveProviderFromUserStatus_REMOVE_PROVIDER_FAILED            RemoveProviderFromUserStatus = 1
	RemoveProviderFromUserStatus_REMOVE_PROVIDER_NOT_FOUND         RemoveProviderFromUserStatus = 2
	RemoveProviderFromUserStatus_REMOVE_PROVIDER_VALIDATION_FAILED RemoveProviderFromUserStatus = 3
)

// Enum value maps for RemoveProviderFromUserStatus.
var (
	RemoveProviderFromUserStatus_name = map[int32]string{
		0: "REMOVE_PROVIDER_SUCCESS",
		1: "REMOVE_PROVIDER_FAILED",
		2: "REMOVE_PROVIDER_NOT_FOUND",
		3: "REMOVE_PROVIDER_VALIDATION_FAILED",
	}
	RemoveProviderFromUserStatus_value = map[string]int32{
		"REMOVE_PROVIDER_SUCCESS":           0,
		"REMOVE_PROVIDER_FAILED":            1,
		"REMOVE_PROVIDER_NOT_FOUND":         2,
		"REMOVE_PROVIDER_VALIDATION_FAILED": 3,
	}
)

func (x RemoveProviderFromUserStatus) Enum() *RemoveProviderFromUserStatus {
	p := new(RemoveProviderFromUserStatus)
	*p = x
	return p
}

func (x RemoveProviderFromUserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoveProviderFromUserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (RemoveProviderFromUserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x RemoveProviderFromUserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoveProviderFromUserStatus.Descriptor instead.
func (RemoveProviderFromUserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type GetUserProvidersStatus int32

const (
	GetUserProvidersStatus_GET_PROVIDERS_SUCCESS           GetUserProvidersStatus = 0
	GetUserProvidersStatus_GET_PROVIDERS_FAILED            GetUserProvidersStatus = 1
	GetUserProvidersStatus_GET_PROVIDERS_NOT_FOUND         GetUserProvidersStatus = 2
	GetUserProvidersStatus_GET_PROVIDERS_VALIDATION_FAILED GetUserProvidersStatus = 3
)

// Enum value maps for GetUserProvidersStatus.
var (
	GetUserProvidersStatus_name = map[int32]string{
		0: "GET_PROVIDERS_SUCCESS",
		1: "GET_PROVIDERS_FAILED",
		2: "GET_PROVIDERS_NOT_FOUND",
		3: "GET_PROVIDERS_VALIDATION_FAILED",
	}
	GetUserProvidersStatus_value = map[string]int32{
		"GET_PROVIDERS_SUCCESS":           0,
		"GET_PROVIDERS_FAILED":            1,
		"GET_PROVIDERS_NOT_FOUND":         2,
		"GET_PROVIDERS_VALIDATION_FAILED": 3,
	}
)

func (x GetUserProvidersStatus) Enum() *GetUserProvidersStatus {
	p := new(GetUserProvidersStatus)
	*p = x
	return p
}

func (x GetUserProvidersStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserProvidersStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[1].Descriptor()
}

func (GetUserProvidersStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[1]
}

func (x GetUserProvidersStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserProvidersStatus.Descriptor instead.
func (GetUserProvidersStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type AddProviderToUserStatus int32

const (
	AddProviderToUserStatus_ADD_PROVIDER_SUCCESS           AddProviderToUserStatus = 0
	AddProviderToUserStatus_ADD_PROVIDER_FAILED            AddProviderToUserStatus = 1
	AddProviderToUserStatus_ADD_PROVIDER_VALIDATION_FAILED AddProviderToUserStatus = 2
)

// Enum value maps for AddProviderToUserStatus.
var (
	AddProviderToUserStatus_name = map[int32]string{
		0: "ADD_PROVIDER_SUCCESS",
		1: "ADD_PROVIDER_FAILED",
		2: "ADD_PROVIDER_VALIDATION_FAILED",
	}
	AddProviderToUserStatus_value = map[string]int32{
		"ADD_PROVIDER_SUCCESS":           0,
		"ADD_PROVIDER_FAILED":            1,
		"ADD_PROVIDER_VALIDATION_FAILED": 2,
	}
)

func (x AddProviderToUserStatus) Enum() *AddProviderToUserStatus {
	p := new(AddProviderToUserStatus)
	*p = x
	return p
}

func (x AddProviderToUserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddProviderToUserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[2].Descriptor()
}

func (AddProviderToUserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[2]
}

func (x AddProviderToUserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddProviderToUserStatus.Descriptor instead.
func (AddProviderToUserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

type CreateUserStatus int32

const (
	CreateUserStatus_CREATED           CreateUserStatus = 0
	CreateUserStatus_CREATE_FAILED     CreateUserStatus = 1
	CreateUserStatus_ALREADY_EXISTS    CreateUserStatus = 2
	CreateUserStatus_VALIDATION_FAILED CreateUserStatus = 3
)

// Enum value maps for CreateUserStatus.
var (
	CreateUserStatus_name = map[int32]string{
		0: "CREATED",
		1: "CREATE_FAILED",
		2: "ALREADY_EXISTS",
		3: "VALIDATION_FAILED",
	}
	CreateUserStatus_value = map[string]int32{
		"CREATED":           0,
		"CREATE_FAILED":     1,
		"ALREADY_EXISTS":    2,
		"VALIDATION_FAILED": 3,
	}
)

func (x CreateUserStatus) Enum() *CreateUserStatus {
	p := new(CreateUserStatus)
	*p = x
	return p
}

func (x CreateUserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateUserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[3].Descriptor()
}

func (CreateUserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[3]
}

func (x CreateUserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateUserStatus.Descriptor instead.
func (CreateUserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

type GetUserResponseStatus int32

const (
	GetUserResponseStatus_SUCCESS   GetUserResponseStatus = 0
	GetUserResponseStatus_FAILED    GetUserResponseStatus = 1
	GetUserResponseStatus_NOT_FOUND GetUserResponseStatus = 2
)

// Enum value maps for GetUserResponseStatus.
var (
	GetUserResponseStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "NOT_FOUND",
	}
	GetUserResponseStatus_value = map[string]int32{
		"SUCCESS":   0,
		"FAILED":    1,
		"NOT_FOUND": 2,
	}
)

func (x GetUserResponseStatus) Enum() *GetUserResponseStatus {
	p := new(GetUserResponseStatus)
	*p = x
	return p
}

func (x GetUserResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[4].Descriptor()
}

func (GetUserResponseStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[4]
}

func (x GetUserResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserResponseStatus.Descriptor instead.
func (GetUserResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

type CopyCardSetStatus int32

const (
	CopyCardSetStatus_COPY_SET_SUCCESS           CopyCardSetStatus = 0
	CopyCardSetStatus_COPY_SET_FAILED            CopyCardSetStatus = 1
	CopyCardSetStatus_COPY_SET_NOT_FOUND         CopyCardSetStatus = 2
	CopyCardSetStatus_COPY_SET_VALIDATION_FAILED CopyCardSetStatus = 3
)

// Enum value maps for CopyCardSetStatus.
var (
	CopyCardSetStatus_name = map[int32]string{
		0: "COPY_SET_SUCCESS",
		1: "COPY_SET_FAILED",
		2: "COPY_SET_NOT_FOUND",
		3: "COPY_SET_VALIDATION_FAILED",
	}
	CopyCardSetStatus_value = map[string]int32{
		"COPY_SET_SUCCESS":           0,
		"COPY_SET_FAILED":            1,
		"COPY_SET_NOT_FOUND":         2,
		"COPY_SET_VALIDATION_FAILED": 3,
	}
)

func (x CopyCardSetStatus) Enum() *CopyCardSetStatus {
	p := new(CopyCardSetStatus)
	*p = x
	return p
}

func (x CopyCardSetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyCardSetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[5].Descriptor()
}

func (CopyCardSetStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[5]
}

func (x CopyCardSetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyCardSetStatus.Descriptor instead.
func (CopyCardSetStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserByProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // google, apple
	ProviderId    *UUID                  `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByProviderRequest) Reset() {
	*x = GetUserByProviderRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByProviderRequest) ProtoMessage() {}

func (x *GetUserByProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByProviderRequest.ProtoReflect.Descriptor instead.
func (*GetUserByProviderRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetUserByProviderRequest) GetProviderId() *UUID {
	if x != nil {
		return x.ProviderId
	}
	return nil
}

type CreateUserWithEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserWithEmailRequest) Reset() {
	*x = CreateUserWithEmailRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserWithEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserWithEmailRequest) ProtoMessage() {}

func (x *CreateUserWithEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserWithEmailRequest.ProtoReflect.Descriptor instead.
func (*CreateUserWithEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserWithEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserWithEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserWithEmailRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateUserWithProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // google, apple
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserWithProviderRequest) Reset() {
	*x = CreateUserWithProviderRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserWithProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserWithProviderRequest) ProtoMessage() {}

func (x *CreateUserWithProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserWithProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateUserWithProviderRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserWithProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateUserWithProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateUserWithProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserWithProviderRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AddProviderToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *UUID                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"` // google, apple
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProviderToUserRequest) Reset() {
	*x = AddProviderToUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProviderToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProviderToUserRequest) ProtoMessage() {}

func (x *AddProviderToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProviderToUserRequest.ProtoReflect.Descriptor instead.
func (*AddProviderToUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *AddProviderToUserRequest) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *AddProviderToUserRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AddProviderToUserRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type AddProviderToUserResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        AddProviderToUserStatus `protobuf:"varint,1,opt,name=status,proto3,enum=user.AddProviderToUserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProviderToUserResponse) Reset() {
	*x = AddProviderToUserResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProviderToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProviderToUserResponse) ProtoMessage() {}

func (x *AddProviderToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProviderToUserResponse.ProtoReflect.Descriptor instead.
func (*AddProviderToUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *AddProviderToUserResponse) GetStatus() AddProviderToUserStatus {
	if x != nil {
		return x.Status
	}
	return AddProviderToUserStatus_ADD_PROVIDER_SUCCESS
}

type RemoveProviderFromUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *UUID                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"` // 'apple', 'google', etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProviderFromUserRequest) Reset() {
	*x = RemoveProviderFromUserRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProviderFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProviderFromUserRequest) ProtoMessage() {}

func (x *RemoveProviderFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProviderFromUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveProviderFromUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveProviderFromUserRequest) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *RemoveProviderFromUserRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type RemoveProviderFromUserResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        RemoveProviderFromUserStatus `protobuf:"varint,1,opt,name=status,proto3,enum=user.RemoveProviderFromUserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProviderFromUserResponse) Reset() {
	*x = RemoveProviderFromUserResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProviderFromUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProviderFromUserResponse) ProtoMessage() {}

func (x *RemoveProviderFromUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProviderFromUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveProviderFromUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveProviderFromUserResponse) GetStatus() RemoveProviderFromUserStatus {
	if x != nil {
		return x.Status
	}
	return RemoveProviderFromUserStatus_REMOVE_PROVIDER_SUCCESS
}

type GetUserProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *UUID                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProvidersRequest) Reset() {
	*x = GetUserProvidersRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProvidersRequest) ProtoMessage() {}

func (x *GetUserProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetUserProvidersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserProvidersRequest) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

type GetUserProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GetUserProvidersStatus `protobuf:"varint,1,opt,name=status,proto3,enum=user.GetUserProvidersStatus" json:"status,omitempty"`
	Providers     []*OAuthProvider       `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProvidersResponse) Reset() {
	*x = GetUserProvidersResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProvidersResponse) ProtoMessage() {}

func (x *GetUserProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetUserProvidersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserProvidersResponse) GetStatus() GetUserProvidersStatus {
	if x != nil {
		return x.Status
	}
	return GetUserProvidersStatus_GET_PROVIDERS_SUCCESS
}

func (x *GetUserProvidersResponse) GetProviders() []*OAuthProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type UpdateUserAchievementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *UUID                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sets          int32                  `protobuf:"varint,2,opt,name=sets,proto3" json:"sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAchievementsRequest) Reset() {
	*x = UpdateUserAchievementsRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAchievementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAchievementsRequest) ProtoMessage() {}

func (x *UpdateUserAchievementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAchievementsRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAchievementsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserAchievementsRequest) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UpdateUserAchievementsRequest) GetSets() int32 {
	if x != nil {
		return x.Sets
	}
	return 0
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OAuthProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`                       // 'apple', 'google', etc.
	ProviderId    string                 `protobuf:"bytes,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // ID от провайдера
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthProvider) Reset() {
	*x = OAuthProvider{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthProvider) ProtoMessage() {}

func (x *OAuthProvider) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthProvider.ProtoReflect.Descriptor instead.
func (*OAuthProvider) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *OAuthProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuthProvider) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OAuthProvider) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthProvider) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *OAuthProvider) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GetUserResponseStatus  `protobuf:"varint,1,opt,name=status,proto3,enum=user.GetUserResponseStatus" json:"status,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	UserId        *UUID                  `protobuf:"bytes,4,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	Providers     []*OAuthProvider       `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty"` // Список всех провайдеров пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserResponse) GetStatus() GetUserResponseStatus {
	if x != nil {
		return x.Status
	}
	return GetUserResponseStatus_SUCCESS
}

func (x *GetUserResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *GetUserResponse) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetUserResponse) GetProviders() []*OAuthProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CreateUserStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=user.CreateUserStatus" json:"status,omitempty"`
	UserId        *UUID                  `protobuf:"bytes,2,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Username      *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserResponse) GetStatus() CreateUserStatus {
	if x != nil {
		return x.Status
	}
	return CreateUserStatus_CREATED
}

func (x *CreateUserResponse) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CreateUserResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateUserResponse) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

type UpdateUserAchievementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GetUserResponseStatus  `protobuf:"varint,1,opt,name=status,proto3,enum=user.GetUserResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAchievementsResponse) Reset() {
	*x = UpdateUserAchievementsResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAchievementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAchievementsResponse) ProtoMessage() {}

func (x *UpdateUserAchievementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAchievementsResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserAchievementsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserAchievementsResponse) GetStatus() GetUserResponseStatus {
	if x != nil {
		return x.Status
	}
	return GetUserResponseStatus_SUCCESS
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GetUserResponseStatus  `protobuf:"varint,1,opt,name=status,proto3,enum=user.GetUserResponseStatus" json:"status,omitempty"`
	Users         []*GetUserResponse     `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *SearchUsersResponse) GetStatus() GetUserResponseStatus {
	if x != nil {
		return x.Status
	}
	return GetUserResponseStatus_SUCCESS
}

func (x *SearchUsersResponse) GetUsers() []*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CopyCardSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *UUID                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SetId         *UUID                  `protobuf:"bytes,2,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyCardSetRequest) Reset() {
	*x = CopyCardSetRequest{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyCardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyCardSetRequest) ProtoMessage() {}

func (x *CopyCardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyCardSetRequest.ProtoReflect.Descriptor instead.
func (*CopyCardSetRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *CopyCardSetRequest) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CopyCardSetRequest) GetSetId() *UUID {
	if x != nil {
		return x.SetId
	}
	return nil
}

type CopyCardSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CopyCardSetStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=user.CopyCardSetStatus" json:"status,omitempty"`
	NewSetId      *UUID                  `protobuf:"bytes,2,opt,name=new_set_id,json=newSetId,proto3,oneof" json:"new_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyCardSetResponse) Reset() {
	*x = CopyCardSetResponse{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyCardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyCardSetResponse) ProtoMessage() {}

func (x *CopyCardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyCardSetResponse.ProtoReflect.Descriptor instead.
func (*CopyCardSetResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *CopyCardSetResponse) GetStatus() CopyCardSetStatus {
	if x != nil {
		return x.Status
	}
	return CopyCardSetStatus_COPY_SET_SUCCESS
}

func (x *CopyCardSetResponse) GetNewSetId() *UUID {
	if x != nil {
		return x.NewSetId
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"c\n" +
	"\x18GetUserByProviderRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12+\n" +
	"\vprovider_id\x18\x02 \x01(\v2\n" +
	".user.UUIDR\n" +
	"providerId\"b\n" +
	"\x1aCreateUserWithEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\x8c\x01\n" +
	"\x1dCreateUserWithProviderRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"|\n" +
	"\x18AddProviderToUserRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\v2\n" +
	".user.UUIDR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\"R\n" +
	"\x19AddProviderToUserResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.user.AddProviderToUserStatusR\x06status\"`\n" +
	"\x1dRemoveProviderFromUserRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\v2\n" +
	".user.UUIDR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\\\n" +
	"\x1eRemoveProviderFromUserResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".user.RemoveProviderFromUserStatusR\x06status\">\n" +
	"\x17GetUserProvidersRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\v2\n" +
	".user.UUIDR\x06userId\"\x83\x01\n" +
	"\x18GetUserProvidersResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.user.GetUserProvidersStatusR\x06status\x121\n" +
	"\tproviders\x18\x02 \x03(\v2\x13.user.OAuthProviderR\tproviders\"X\n" +
	"\x1dUpdateUserAchievementsRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\v2\n" +
	".user.UUIDR\x06userId\x12\x12\n" +
	"\x04sets\x18\x02 \x01(\x05R\x04sets\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x94\x01\n" +
	"\rOAuthProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xfd\x01\n" +
	"\x0fGetUserResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.user.GetUserResponseStatusR\x06status\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x01R\busername\x88\x01\x01\x12'\n" +
	"\x06userId\x18\x04 \x01(\v2\n" +
	".user.UUIDH\x02R\x06userId\x88\x01\x01\x121\n" +
	"\tproviders\x18\x05 \x03(\v2\x13.user.OAuthProviderR\tprovidersB\a\n" +
	"\x05_nameB\v\n" +
	"\t_usernameB\t\n" +
	"\a_userId\"\xc8\x01\n" +
	"\x12CreateUserResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.user.CreateUserStatusR\x06status\x12'\n" +
	"\x06userId\x18\x02 \x01(\v2\n" +
	".user.UUIDH\x00R\x06userId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01B\t\n" +
	"\a_userIdB\a\n" +
	"\x05_nameB\v\n" +
	"\t_username\"U\n" +
	"\x1eUpdateUserAchievementsResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.user.GetUserResponseStatusR\x06status\"X\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8d\x01\n" +
	"\x13SearchUsersResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.user.GetUserResponseStatusR\x06status\x12+\n" +
	"\x05users\x18\x02 \x03(\v2\x15.user.GetUserResponseR\x05users\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\\\n" +
	"\x12CopyCardSetRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\v2\n" +
	".user.UUIDR\x06userId\x12!\n" +
	"\x06set_id\x18\x02 \x01(\v2\n" +
	".user.UUIDR\x05setId\"\x84\x01\n" +
	"\x13CopyCardSetResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.user.CopyCardSetStatusR\x06status\x12-\n" +
	"\n" +
	"new_set_id\x18\x02 \x01(\v2\n" +
	".user.UUIDH\x00R\bnewSetId\x88\x01\x01B\r\n" +
	"\v_new_set_id*\x9d\x01\n" +
	"\x1cRemoveProviderFromUserStatus\x12\x1b\n" +
	"\x17REMOVE_PROVIDER_SUCCESS\x10\x00\x12\x1a\n" +
	"\x16REMOVE_PROVIDER_FAILED\x10\x01\x12\x1d\n" +
	"\x19REMOVE_PROVIDER_NOT_FOUND\x10\x02\x12%\n" +
	"!REMOVE_PROVIDER_VALIDATION_FAILED\x10\x03*\x8f\x01\n" +
	"\x16GetUserProvidersStatus\x12\x19\n" +
	"\x15GET_PROVIDERS_SUCCESS\x10\x00\x12\x18\n" +
	"\x14GET_PROVIDERS_FAILED\x10\x01\x12\x1b\n" +
	"\x17GET_PROVIDERS_NOT_FOUND\x10\x02\x12#\n" +
	"\x1fGET_PROVIDERS_VALIDATION_FAILED\x10\x03*p\n" +
	"\x17AddProviderToUserStatus\x12\x18\n" +
	"\x14ADD_PROVIDER_SUCCESS\x10\x00\x12\x17\n" +
	"\x13ADD_PROVIDER_FAILED\x10\x01\x12\"\n" +
	"\x1eADD_PROVIDER_VALIDATION_FAILED\x10\x02*]\n" +
	"\x10CreateUserStatus\x12\v\n" +
	"\aCREATED\x10\x00\x12\x11\n" +
	"\rCREATE_FAILED\x10\x01\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x02\x12\x15\n" +
	"\x11VALIDATION_FAILED\x10\x03*?\n" +
	"\x15GetUserResponseStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02*v\n" +
	"\x11CopyCardSetStatus\x12\x14\n" +
	"\x10COPY_SET_SUCCESS\x10\x00\x12\x13\n" +
	"\x0fCOPY_SET_FAILED\x10\x01\x12\x16\n" +
	"\x12COPY_SET_NOT_FOUND\x10\x02\x12\x1e\n" +
	"\x1aCOPY_SET_VALIDATION_FAILED\x10\x032\xe1\x05\n" +
	"\vUserService\x12D\n" +
	"\x0eGetUserByEmail\x12\x1b.user.GetUserByEmailRequest\x1a\x15.user.GetUserResponse\x12J\n" +
	"\x11GetUserByProvider\x12\x1e.user.GetUserByProviderRequest\x1a\x15.user.GetUserResponse\x12Q\n" +
	"\x13CreateUserWithEmail\x12 .user.CreateUserWithEmailRequest\x1a\x18.user.CreateUserResponse\x12W\n" +
	"\x16CreateUserWithProvider\x12#.user.CreateUserWithProviderRequest\x1a\x18.user.CreateUserResponse\x12T\n" +
	"\x11AddProviderToUser\x12\x1e.user.AddProviderToUserRequest\x1a\x1f.user.AddProviderToUserResponse\x12c\n" +
	"\x16RemoveProviderFromUser\x12#.user.RemoveProviderFromUserRequest\x1a$.user.RemoveProviderFromUserResponse\x12Q\n" +
	"\x10GetUserProviders\x12\x1d.user.GetUserProvidersRequest\x1a\x1e.user.GetUserProvidersResponse\x12B\n" +
	"\vSearchUsers\x12\x18.user.SearchUsersRequest\x1a\x19.user.SearchUsersResponse\x12B\n" +
	"\vCopyCardSet\x12\x18.user.CopyCardSetRequest\x1a\x19.user.CopyCardSetResponse2r\n" +
	"\vCardService\x12c\n" +
	"\x16UpdateUserAchievements\x12#.user.UpdateUserAchievementsRequest\x1a$.user.UpdateUserAchievementsResponseB\x0fZ\r./userserviceb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_proto_goTypes = []any{
	(RemoveProviderFromUserStatus)(0),      // 0: user.RemoveProviderFromUserStatus
	(GetUserProvidersStatus)(0),            // 1: user.GetUserProvidersStatus
	(AddProviderToUserStatus)(0),           // 2: user.AddProviderToUserStatus
	(CreateUserStatus)(0),                  // 3: user.CreateUserStatus
	(GetUserResponseStatus)(0),             // 4: user.GetUserResponseStatus
	(CopyCardSetStatus)(0),                 // 5: user.CopyCardSetStatus
	(*GetUserByEmailRequest)(nil),          // 6: user.GetUserByEmailRequest
	(*GetUserByProviderRequest)(nil),       // 7: user.GetUserByProviderRequest
	(*CreateUserWithEmailRequest)(nil),     // 8: user.CreateUserWithEmailRequest
	(*CreateUserWithProviderRequest)(nil),  // 9: user.CreateUserWithProviderRequest
	(*AddProviderToUserRequest)(nil),       // 10: user.AddProviderToUserRequest
	(*AddProviderToUserResponse)(nil),      // 11: user.AddProviderToUserResponse
	(*RemoveProviderFromUserRequest)(nil),  // 12: user.RemoveProviderFromUserRequest
	(*RemoveProviderFromUserResponse)(nil), // 13: user.RemoveProviderFromUserResponse
	(*GetUserProvidersRequest)(nil),        // 14: user.GetUserProvidersRequest
	(*GetUserProvidersResponse)(nil),       // 15: user.GetUserProvidersResponse
	(*UpdateUserAchievementsRequest)(nil),  // 16: user.UpdateUserAchievementsRequest
	(*UUID)(nil),                           // 17: user.UUID
	(*OAuthProvider)(nil),                  // 18: user.OAuthProvider
	(*GetUserResponse)(nil),                // 19: user.GetUserResponse
	(*CreateUserResponse)(nil),             // 20: user.CreateUserResponse
	(*UpdateUserAchievementsResponse)(nil), // 21: user.UpdateUserAchievementsResponse
	(*SearchUsersRequest)(nil),             // 22: user.SearchUsersRequest
	(*SearchUsersResponse)(nil),            // 23: user.SearchUsersResponse
	(*CopyCardSetRequest)(nil),             // 24: user.CopyCardSetRequest
	(*CopyCardSetResponse)(nil),            // 25: user.CopyCardSetResponse
}
var file_user_proto_depIdxs = []int32{
	17, // 0: user.GetUserByProviderRequest.provider_id:type_name -> user.UUID
	17, // 1: user.AddProviderToUserRequest.user_id:type_name -> user.UUID
	2,  // 2: user.AddProviderToUserResponse.status:type_name -> user.AddProviderToUserStatus
	17, // 3: user.RemoveProviderFromUserRequest.user_id:type_name -> user.UUID
	0,  // 4: user.RemoveProviderFromUserResponse.status:type_name -> user.RemoveProviderFromUserStatus
	17, // 5: user.GetUserProvidersRequest.user_id:type_name -> user.UUID
	1,  // 6: user.GetUserProvidersResponse.status:type_name -> user.GetUserProvidersStatus
	18, // 7: user.GetUserProvidersResponse.providers:type_name -> user.OAuthProvider
	17, // 8: user.UpdateUserAchievementsRequest.user_id:type_name -> user.UUID
	4,  // 9: user.GetUserResponse.status:type_name -> user.GetUserResponseStatus
	17, // 10: user.GetUserResponse.userId:type_name -> user.UUID
	18, // 11: user.GetUserResponse.providers:type_name -> user.OAuthProvider
	3,  // 12: user.CreateUserResponse.status:type_name -> user.CreateUserStatus
	17, // 13: user.CreateUserResponse.userId:type_name -> user.UUID
	4,  // 14: user.UpdateUserAchievementsResponse.status:type_name -> user.GetUserResponseStatus
	4,  // 15: user.SearchUsersResponse.status:type_name -> user.GetUserResponseStatus
	19, // 16: user.SearchUsersResponse.users:type_name -> user.GetUserResponse
	17, // 17: user.CopyCardSetRequest.user_id:type_name -> user.UUID
	17, // 18: user.CopyCardSetRequest.set_id:type_name -> user.UUID
	5,  // 19: user.CopyCardSetResponse.status:type_name -> user.CopyCardSetStatus
	17, // 20: user.CopyCardSetResponse.new_set_id:type_name -> user.UUID
	6,  // 21: user.UserService.GetUserByEmail:input_type -> user.GetUserByEmailRequest
	7,  // 22: user.UserService.GetUserByProvider:input_type -> user.GetUserByProviderRequest
	8,  // 23: user.UserService.CreateUserWithEmail:input_type -> user.CreateUserWithEmailRequest
	9,  // 24: user.UserService.CreateUserWithProvider:input_type -> user.CreateUserWithProviderRequest
	10, // 25: user.UserService.AddProviderToUser:input_type -> user.AddProviderToUserRequest
	12, // 26: user.UserService.RemoveProviderFromUser:input_type -> user.RemoveProviderFromUserRequest
	14, // 27: user.UserService.GetUserProviders:input_type -> user.GetUserProvidersRequest
	22, // 28: user.UserService.SearchUsers:input_type -> user.SearchUsersRequest
	24, // 29: user.UserService.CopyCardSet:input_type -> user.CopyCardSetRequest
	16, // 30: user.CardService.UpdateUserAchievements:input_type -> user.UpdateUserAchievementsRequest
	19, // 31: user.UserService.GetUserByEmail:output_type -> user.GetUserResponse
	19, // 32: user.UserService.GetUserByProvider:output_type -> user.GetUserResponse
	20, // 33: user.UserService.CreateUserWithEmail:output_type -> user.CreateUserResponse
	20, // 34: user.UserService.CreateUserWithProvider:output_type -> user.CreateUserResponse
	11, // 35: user.UserService.AddProviderToUser:output_type -> user.AddProviderToUserResponse
	13, // 36: user.UserService.RemoveProviderFromUser:output_type -> user.RemoveProviderFromUserResponse
	15, // 37: user.UserService.GetUserProviders:output_type -> user.GetUserProvidersResponse
	23, // 38: user.UserService.SearchUsers:output_type -> user.SearchUsersResponse
	25, // 39: user.UserService.CopyCardSet:output_type -> user.CopyCardSetResponse
	21, // 40: user.CardService.UpdateUserAchievements:output_type -> user.UpdateUserAchievementsResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[13].OneofWrappers = []any{}
	file_user_proto_msgTypes[14].OneofWrappers = []any{}
	file_user_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
