// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/file_storage.proto

package filestorage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileStorageService_UploadFile_FullMethodName     = "/filestorage.FileStorageService/UploadFile"
	FileStorageService_UploadInit_FullMethodName     = "/filestorage.FileStorageService/UploadInit"
	FileStorageService_UploadPart_FullMethodName     = "/filestorage.FileStorageService/UploadPart"
	FileStorageService_UploadComplete_FullMethodName = "/filestorage.FileStorageService/UploadComplete"
	FileStorageService_UploadAbort_FullMethodName    = "/filestorage.FileStorageService/UploadAbort"
	FileStorageService_GetFile_FullMethodName        = "/filestorage.FileStorageService/GetFile"
	FileStorageService_DeleteFile_FullMethodName     = "/filestorage.FileStorageService/DeleteFile"
)

// FileStorageServiceClient is the client API for FileStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FileStorageService предоставляет методы для работы с файлами
type FileStorageServiceClient interface {
	// Загрузка файла (простая, для маленьких файлов)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	// Инициализация многокомпонентной загрузки
	UploadInit(ctx context.Context, in *UploadInitRequest, opts ...grpc.CallOption) (*UploadInitResponse, error)
	// Загрузка части файла
	UploadPart(ctx context.Context, in *UploadPartRequest, opts ...grpc.CallOption) (*UploadPartResponse, error)
	// Завершение многокомпонентной загрузки
	UploadComplete(ctx context.Context, in *UploadCompleteRequest, opts ...grpc.CallOption) (*UploadCompleteResponse, error)
	// Отмена загрузки
	UploadAbort(ctx context.Context, in *UploadAbortRequest, opts ...grpc.CallOption) (*UploadAbortResponse, error)
	// Получение информации о файле
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	// Удаление файла
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
}

type fileStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileStorageServiceClient(cc grpc.ClientConnInterface) FileStorageServiceClient {
	return &fileStorageServiceClient{cc}
}

func (c *fileStorageServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, FileStorageService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) UploadInit(ctx context.Context, in *UploadInitRequest, opts ...grpc.CallOption) (*UploadInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadInitResponse)
	err := c.cc.Invoke(ctx, FileStorageService_UploadInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) UploadPart(ctx context.Context, in *UploadPartRequest, opts ...grpc.CallOption) (*UploadPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPartResponse)
	err := c.cc.Invoke(ctx, FileStorageService_UploadPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) UploadComplete(ctx context.Context, in *UploadCompleteRequest, opts ...grpc.CallOption) (*UploadCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadCompleteResponse)
	err := c.cc.Invoke(ctx, FileStorageService_UploadComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) UploadAbort(ctx context.Context, in *UploadAbortRequest, opts ...grpc.CallOption) (*UploadAbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAbortResponse)
	err := c.cc.Invoke(ctx, FileStorageService_UploadAbort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, FileStorageService_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, FileStorageService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileStorageServiceServer is the server API for FileStorageService service.
// All implementations must embed UnimplementedFileStorageServiceServer
// for forward compatibility.
//
// FileStorageService предоставляет методы для работы с файлами
type FileStorageServiceServer interface {
	// Загрузка файла (простая, для маленьких файлов)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	// Инициализация многокомпонентной загрузки
	UploadInit(context.Context, *UploadInitRequest) (*UploadInitResponse, error)
	// Загрузка части файла
	UploadPart(context.Context, *UploadPartRequest) (*UploadPartResponse, error)
	// Завершение многокомпонентной загрузки
	UploadComplete(context.Context, *UploadCompleteRequest) (*UploadCompleteResponse, error)
	// Отмена загрузки
	UploadAbort(context.Context, *UploadAbortRequest) (*UploadAbortResponse, error)
	// Получение информации о файле
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	// Удаление файла
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	mustEmbedUnimplementedFileStorageServiceServer()
}

// UnimplementedFileStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileStorageServiceServer struct{}

func (UnimplementedFileStorageServiceServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileStorageServiceServer) UploadInit(context.Context, *UploadInitRequest) (*UploadInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadInit not implemented")
}
func (UnimplementedFileStorageServiceServer) UploadPart(context.Context, *UploadPartRequest) (*UploadPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedFileStorageServiceServer) UploadComplete(context.Context, *UploadCompleteRequest) (*UploadCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadComplete not implemented")
}
func (UnimplementedFileStorageServiceServer) UploadAbort(context.Context, *UploadAbortRequest) (*UploadAbortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAbort not implemented")
}
func (UnimplementedFileStorageServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFileStorageServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileStorageServiceServer) mustEmbedUnimplementedFileStorageServiceServer() {}
func (UnimplementedFileStorageServiceServer) testEmbeddedByValue()                            {}

// UnsafeFileStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileStorageServiceServer will
// result in compilation errors.
type UnsafeFileStorageServiceServer interface {
	mustEmbedUnimplementedFileStorageServiceServer()
}

func RegisterFileStorageServiceServer(s grpc.ServiceRegistrar, srv FileStorageServiceServer) {
	// If the following call panics, it indicates UnimplementedFileStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileStorageService_ServiceDesc, srv)
}

func _FileStorageService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_UploadInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).UploadInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_UploadInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).UploadInit(ctx, req.(*UploadInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_UploadPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).UploadPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_UploadPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).UploadPart(ctx, req.(*UploadPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_UploadComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).UploadComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_UploadComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).UploadComplete(ctx, req.(*UploadCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_UploadAbort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).UploadAbort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_UploadAbort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).UploadAbort(ctx, req.(*UploadAbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileStorageService_ServiceDesc is the grpc.ServiceDesc for FileStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filestorage.FileStorageService",
	HandlerType: (*FileStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFile",
			Handler:    _FileStorageService_UploadFile_Handler,
		},
		{
			MethodName: "UploadInit",
			Handler:    _FileStorageService_UploadInit_Handler,
		},
		{
			MethodName: "UploadPart",
			Handler:    _FileStorageService_UploadPart_Handler,
		},
		{
			MethodName: "UploadComplete",
			Handler:    _FileStorageService_UploadComplete_Handler,
		},
		{
			MethodName: "UploadAbort",
			Handler:    _FileStorageService_UploadAbort_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _FileStorageService_GetFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileStorageService_DeleteFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/file_storage.proto",
}
